config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :symptoms
  resources :categories
  resources :conditions
  resources :users
  resources :medications do
    resources :conditions, only: [:new, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :medications
    has_many :users, through: :medications

    validates :name, presence: true, uniqueness: true

    scope :alpha, -> {order(:name)}
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :user
  belongs_to :medication
  has_many :symptoms

  validates :name, presence: true
  validates :notes, presence: true
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :conditions
  has_many :users, through: :conditions

  validates :name, presence: true
  validates :dosage, presence: true
  validates :units, presence: true
  validates :frequency, presence: true
  validates :times_per_day, presence: true
  validates :start_date, presence: true
  validate :not_a_duplicate

  scope :alpha, -> {order(:name)}

  # def self.filter(params)
  #   where("category_id = ?", params)
  # end
  
  def self.search(params)
    joins(:category).where("LOWER(medications.name) LIKE :term OR LOWER(categories.name) LIKE :term", term: "%#{params}%")
  end
 
  def category_attributes=(attributes)
    self.category = Category.find_or_create_by(attributes) if !attributes['name'].empty?
    self.category
  end

  def not_a_duplicate
    medication = Medication.find_by(name: name, category_id: category_id)
    if !!medication && medication != self
      errors.add(:name, "has already been added for that category")
    end
  end

  def name_and_category
    "#{name} - #{category.name}"
  end

end

app/models/symptom.rb
class Symptom < ApplicationRecord
    belongs_to :condition
end

app/models/user.rb
class User < ApplicationRecord
    has_many :conditions
    has_many :conditioned_medications, through: :conditions, source: :medication
    has_many :medications
    has_many :categories, through: :medications

    has_secure_password

    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true

    def self.from_google_omniauth(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |user|
            user.username = auth[:info][:name]
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to login_path if !logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @categories = Category.alpha
    end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        if @medication = Medication.find_by_id(params[:medication_id])
            @condition = @medication.conditions.build
        else
            @condition = Condition.new
        end
    end

    def create
        @condition = current_user.conditions.build(condition_params)
        if @condition.save
            redirect_to condition_path(@condition)
        else
            render :new
        end
    end

    def show
        @condition = Condition.find_by_id(params[:id])
    end

    def index
        if @medication = Medication.find_by_id(params[:medication_id])
            @conditions = @medication.conditions
        else
            @conditions = Condition.where(:user_id => current_user.id)
        end
    end

    private

    def condition_params
       params.require(:condition).permit(:name, :notes, :medication_id)
    end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
    before_action :set_medication, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_logged_in

    def index
        @medications = Medication.alpha.where(:user_id => current_user.id)

        @medications = @medications.search(params[:q].downcase) if params[:q] && !params[:q].empty?
        #@medications = @medications.filter(params[:medication][:category_id]) if params[:medication] && params[:medication][:category_id]
    end

    def new
        @medication = Medication.new
        @medication.build_category
    end

    def create
        @medication = Medication.new(medication_params)
        @medication.user_id = session[:user_id]
        if @medication.save
            redirect_to medication_path(@medication)
        else
            @medication.build_category
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @medication.update(medication_params)
            redirect_to medication_path(@medication)
        else
            render :edit
        end
    end

    def destroy
        @medication.destroy
        redirect_to medications_path
    end

    private

    def medication_params
        params.require(:medication).permit(:name, :dosage, :units, :frequency, :times_per_day, :start_date, :category_id, category_attributes: [:name])
    end

    def set_medication
        @medication = Medication.find_by_id(params[:id])
        redirect_to medications_path if !@medication
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username].downcase)
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Sorry, username/password combination does not match. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  def omniauth
    @user = User.from_google_omniauth(auth)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
    def new
        @symptom = Symptom.new
    end

    def create
        @symptom = Symptom.new(symptom_params)
        if @symptom.save
            redirect_to symptom_path(@symptom)
        else
            render :new
        end
    end


    private

    def symptom_params
        params.require(:symptom).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
    def header_display(condition)
        if params[:medication_id]
            content_tag(:h1, "Add a Condition for #{@condition.medication.name} - #{@condition.medication.category.name}")
        else 
            content_tag(:h1, "Create a Condition")
        end
    end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conditions/index.html.erb
<div class="conditions">
    <h1>All Medical Conditions</h1><br>
    
    <ul>
        <% @conditions.each do |c| %>
            <li><strong><%= c.name %></strong> - <%= c.notes %><br> 
                Medication: <strong><%= c.medication.name %></strong></li><br>
        <% end %>
    </ul>
    <br>
</div>

app/views/conditions/new.html.erb
<div class="condition-new">
<%= header_display(@condition) %>

<%= render partial: 'layouts/errors', locals: {object: @condition} %>


<%= form_for @condition do |f| %> 
    <% if params[:medication_id] %>
        <%= f.hidden_field :medication_id %>
    <% else %>
        <%= f.label :medication_id, "Select a Medication" %>
        <%= f.collection_select :medication_id, Medication.alpha.where(:user_id => current_user.id), :id, :name_and_category, prompt: true %>
        <br><br>
    <% end %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <br><br>
    
    <%= f.label :notes %>
    <%= f.text_area :notes %><br>
    
    <br><br>

    <%= f.submit 'Create Condition' %>  
<% end %>
</div>

app/views/conditions/show.html.erb
<div class="condition-show">
<h1><%= @condition.name %></h1>
<p><%= @condition.notes %></p>
</div>

app/views/medications/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @medication} %>

<%= form_for @medication do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :dosage %>
    <%= f.text_field :dosage %>

    <%= f.label :units %>
    <%= f.select(:units, ["cc", "ml", "gr", "mg", "mcg", "patch", "tsp", "tbsp", "Pills", "Drops", "Puffs", "Units", "Spray"], prompt: true) %><br><br>

    <%= f.label :frequency %>
    <%= f.select(:frequency, ["As Needed", "Daily", "Every Other Day", "Specific Days"], prompt: true) %><br><br>

    <%= f.label :times_per_day %>
    <%= f.number_field :times_per_day, min:1, max:10 %><br><br>

    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
    <br><br>

    <p> Select a Category that already exists: </p>
    <div>
    <%= f.collection_select :category_id, Category.alpha, :id, :name, prompt: true %>
    </div>

    <p> Or create a new Category: </p>
    
    <%= f.fields_for :category do |c| %>
        <%= c.label :name %>
        <%= c.text_field :name %>
    <% end %>
    <br><br>
    <%= f.submit %>
    
<% end %>

app/views/medications/edit.html.erb
<div class="med-edit">
    <h1>Update Medication</h1><br>
    <%= render 'medications/form' %>
</div>

app/views/medications/index.html.erb
<div class="medications">
<h1> All Medications </h1>
<br><br>


<% @medications.each do |m| %>
    <h3><%= m.name %> <%= m.dosage %><%= m.units %> - <%= m.category.name %> 
    <%= link_to "View Details", medication_path(m) %></h3>
<% end %>
</div>

app/views/medications/new.html.erb
<div class="medication-new">
<h1>Add a New Medication</h1>

<%= render 'medications/form' %>
</div>

app/views/medications/show.html.erb
<div class="medshow">
    <h1><%= @medication.name %> - <%= @medication.category.name %></h1><br>
    <p><strong>Dosage: </strong><%= @medication.dosage %></p>
    <p><strong>Units: </strong><%= @medication.units %></p>
    <p><strong>Frequency: </strong><%= @medication.frequency %></p>
    <p><strong>Times Per Day: </strong><%= @medication.times_per_day %></p>
    <p><strong>Start Date: </strong><%= @medication.start_date %></p>

    <%= link_to "View Conditions for This Medication", medication_conditions_path(@medication.id) %><br>
    <%= link_to "Add Medical Condition", new_medication_condition_path(@medication.id) %>

    <br><br>
    <%= link_to "Edit Medication", edit_medication_path(@medication) %>
    <%= link_to "Delete Medication", medication_path(@medication), method: :delete %>
    <br><br>
    <%= link_to "All Medications", medications_path %>
</div>

app/views/symptoms/new.html.erb
<h1>Create a Symptom</h1>

<%= form_for @symptom do |f| %>
    <%= f.label :name, 'Symptom name' %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<div class="signup">
<h1>Sign Up!</h1>


<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for @user do |f| %>
    <%= f.label :username %>:
    <%= f.text_field :username %><br><br>
    <%= f.label :email %>:
    <%= f.email_field :email %><br><br>
    <%= f.label :password %>:
    <%= f.password_field :password %>
    <br><br>
    <%= f.submit 'Sign Up' %>
    <br><br>
    <%= link_to 'Log In', login_path %><br>
    <%= link_to 'Log In with Google', '/auth/google_oauth2' %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="user-show">
<h1>Welcome <%= @user.username %>!</h1><br>

<h4>You currently have <strong><%= @user.medications.count %></strong> medications listed.</h4><br>
<p> Please choose one of the following: </p>

<%= link_to 'View Medications', medications_path %><br>
<%= link_to 'Add a New Medical Condition', new_condition_path %><br>
<%= link_to 'View All Medical Conditions', conditions_path %><br>
</div>