config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :symptoms
  resources :categories
  resources :conditions
  resources :users
  resources :medications do
    resources :conditions, only: [:new, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :medications
    has_many :users, through: :medications

    validates :name, presence: true, uniqueness: true

    scope :alpha, -> {order(:name)}
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :user
  belongs_to :medication
  has_many :symptoms

  validates :name, presence: true
  validates :notes, presence: true
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :conditions
  has_many :users, through: :conditions

  validates :name, presence: true
  validates :dosage, presence: true
  validates :units, presence: true
  validates :frequency, presence: true
  validates :times_per_day, presence: true
  validates :start_date, presence: true
  validate :not_a_duplicate

  scope :alpha, -> {order(:name)}

  # def self.filter(params)
  #   where("category_id = ?", params)
  # end
  
  def self.search(params)
    joins(:category).where("LOWER(medications.name) LIKE :term OR LOWER(categories.name) LIKE :term", term: "%#{params}%")
  end
 
  def category_attributes=(attributes)
    self.category = Category.find_or_create_by(attributes) if !attributes['name'].empty?
    self.category
  end

  def not_a_duplicate
    medication = Medication.find_by(name: name, category_id: category_id)
    if !!medication && medication != self
      errors.add(:name, "has already been added for that category")
    end
  end

  def name_and_category
    "#{name} - #{category.name}"
  end

end

app/models/symptom.rb
class Symptom < ApplicationRecord
    belongs_to :condition
end

app/models/user.rb
class User < ApplicationRecord
    has_many :conditions
    has_many :conditioned_medications, through: :conditions, source: :medication
    has_many :medications
    has_many :categories, through: :medications

    has_secure_password

    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true

    def self.from_google_omniauth(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |user|
            user.username = auth[:info][:name]
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @categories = Category.alpha
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username].downcase)
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Sorry, username/password combination does not match. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  def omniauth
    @user = User.from_google_omniauth(auth)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
    def new
        @symptom = Symptom.new
    end

    def create
        @symptom = Symptom.new(symptom_params)
        if @symptom.save
            redirect_to symptom_path(@symptom)
        else
            render :new
        end
    end


    private

    def symptom_params
        params.require(:symptom).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
    def header_display(condition)
        if params[:medication_id]
            content_tag(:h1, "Add a Condition for #{@condition.medication.name} - #{@condition.medication.category.name}")
        else 
            content_tag(:h1, "Create a Condition")
        end
    end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>

  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" <%= link_to 'MedList', root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">

    <% if logged_in? %>
        <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Add Medication', new_medication_path %><span class="sr-only">(current)</span></a>   
        </li>

        <li class="nav-item active">
        <a class="nav-link" <%= link_to 'My Profile', user_path(current_user) %><span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Log Out', logout_path, method: :delete %><span class="sr-only">(current)</span></a>
        </li>

        <div class="form-inline my-2 my-lg-0">
          <%= form_tag("/medications", method: "get") do %>
            <%= text_field_tag :q, params[:q], placeholder: "Search Medication"%>
            <%= submit_tag("Search") %>
          <% end %>
        <div>
        
         <%# form_tag("/medications", method: "get") do %>
           <%# collection_select(:medication, :category_id, Category.all, :id, :name, prompt: 'Search by Category') %>
           <%# submit_tag("Filter") %>
         <%# end %>
        

    <% else %>
        <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Sign Up', signup_path %><span class="sr-only">(current)</span></a>   
        </li>

        <li class="nav-item active">
        <a class="nav-link" <%= link_to 'Log In', login_path %><span class="sr-only">(current)</span></a>
        </li>

    <% end %>
    
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

  </body>
</html>